# Generated by Django 3.2.7 on 2023-02-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimyou', '0004_goodtest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goodtest',
            constraint=models.UniqueConstraint(fields=('target', 'user'), name='lesson_unique'),
        ),
    ]
