# Generated by Django 3.2.7 on 2023-02-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jimyou', '0006_auto_20230208_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtest',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jimyou.postmain'),
        ),
    ]
