# Generated by Django 3.2.7 on 2023-02-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jimyou', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endcontents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.TextField(max_length=1000)),
                ('high', models.TextField(max_length=1000)),
                ('insurance', models.TextField(max_length=1000)),
                ('bank', models.TextField(max_length=1000)),
                ('bankpassword', models.TextField(max_length=1000)),
                ('phone', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jimyou.postmain'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=150),
        ),
    ]
