# Generated by Django 3.2.7 on 2023-02-16 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jimyou', '0009_auto_20230216_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.TextField(max_length=1000)),
                ('high', models.TextField(max_length=1000)),
                ('insurance', models.TextField(max_length=1000)),
                ('bank', models.TextField(max_length=1000)),
                ('bankpassword', models.TextField(max_length=1000)),
                ('phone', models.TextField(max_length=1000)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Endcontents',
        ),
    ]
