# Generated by Django 3.2.7 on 2023-02-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimyou', '0010_auto_20230216_1407'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contents',
            constraint=models.UniqueConstraint(fields=('writer',), name='contents_unique'),
        ),
    ]
